repos:
  - repo: local
    hooks:
      - id: yapf
        name: Format Python via yapf
        entry: yapf --in-place --recursive --style="{indent_width: 2}"
        language: python
        types: [python]
        pass_filenames: true
        always_run: true
